
/* Autogenerated */
// ./genh.pl Albert "14-Mar-1879" 

#define NAME "Albert"

static const uint32_t magic_minutes = 421920;	
static const struct date the_birth = {
	1879,
	3,
	14,
	00,
	00
};
static const struct age start_age = {
	0,
	0,
	41,
	6,
	0,
	0
};
