#!/usr/bin/perl -w
#
#
use strict;
use warnings;

use Date::Manip;

if (scalar(@ARGV) != 2) {
    die "Usage: $0 <name> <date>\n";
}
my $name = $ARGV[0];
my $date = $ARGV[1];

my $d = ParseDate($date) || die "couldn't parse date";
my $year = ParseDate(UnixDate($d, "%Y") + 1);
my $str = UnixDate($d, "\t%Y,\n\t%m,\n\t%e,\n\t%H,\n\t%M");

$str =~ s/([ \t]*)0+([1-9]+,)/$1$2/mg;

my $err;
my $delta = DateCalc($d, $year, \$err, 0);
my $sag = Delta_Format($delta, "\t%yv,\n\t%Mv,\n\t%wv,\n\t%dv,\n\t%hv,\n\t%mv");

$sag =~ s/([ \t]*)0+([1-9]+,)/$1$2/mg;

print "
/* Autogenerated */
// $0 $name \"$date\" 

#define NAME \"$name\"

static const struct date the_birth = {
$str
};
static const struct age start_age = {
$sag
};
";
